"""Security linter and attack surface vulnerability scanner for JWT/JWS tokens.

Audits tokens for:
- Algorithm "none" bypass vulnerabilities (CVE-2015-9235)
- Public key / HMAC key confusion attacks (CVE-2016-5431 / CVE-2018-0114)
- Path traversal and SQL injection vectors in 'kid' headers
- Rogue JWKS URL injection in 'jku' and 'x5u' headers
- Embedded JWK injection ('jwk' in header)
- Trivially crackable weak secrets via a 500+ word dictionary
- Sensitive PII / credential leakage in unencrypted payloads
- Missing, excessive, or abnormal token expiration timelines
- Signature stripping attacks
"""

from __future__ import annotations

import re
import time
from typing import Any, Dict, List, Optional, Set, Tuple, Union

from .crypto_engine import calculate_token_entropy, crack_hmac_secret
from .models import (
    DecodedJWT,
    JWTAlgorithm,
    SecurityAuditReport,
    SecuritySeverity,
    SecurityVulnerability,
)
from .token_parser import parse_jwt


# Built-in dictionary of 500+ common JWT secrets, default passwords, and framework keys
COMMON_SECRET_DICTIONARY: Tuple[str, ...] = (
    # Top tier common secrets
    "secret",
    "password",
    "123456",
    "12345678",
    "123456789",
    "jwt",
    "jwtsecret",
    "jwt_secret",
    "jwt-secret",
    "admin",
    "administrator",
    "root",
    "toor",
    "development",
    "dev",
    "test",
    "testing",
    "staging",
    "production",
    "prod",
    "changeme",
    "letmein",
    "welcome",
    "welcome1",
    "master",
    "iloveyou",
    "supersecret",
    "app_secret",
    "appsecret",
    "secret_key",
    "secretkey",
    "mysecret",
    "mysecretkey",
    "default",
    "demo",
    "sample",
    "111111",
    "000000",
    "123123",
    "qwerty",
    "qwertyuiop",
    "auth0",
    "firebase",
    "supabase",
    "hasura",
    "strapi",
    "nextauth",
    "express",
    "django",
    "flask",
    "rails",
    "laravel",
    "spring",
    "key",
    "private",
    "token",
    "access_token",
    "api_secret",
    "api_key",
    "secret123",
    "password123",
    "admin123",
    "root123",
    "pass123",
    "test1234",
    "dev123",
    "secret1",
    "password1",
    "admin1",
    "test1",
    "user",
    "guest",
    "public",
    "temp",
    "local",
    "localhost",
    "server",
    "backend",
    "frontend",
    "database",
    "service",
    "internal",
    "system",
    "oracle",
    "postgres",
    "mysql",
    "mongodb",
    "redis",
    "node",
    "python",
    "golang",
    "rust",
    "docker",
    "k8s",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "cloud",
    # Common English words and strings often used as secrets
    "about",
    "above",
    "across",
    "action",
    "activity",
    "address",
    "advance",
    "after",
    "again",
    "agent",
    "agree",
    "ahead",
    "alarm",
    "album",
    "alert",
    "alive",
    "allow",
    "almost",
    "alone",
    "along",
    "alpha",
    "already",
    "also",
    "always",
    "among",
    "amount",
    "anchor",
    "ancient",
    "angel",
    "anger",
    "angle",
    "animal",
    "annual",
    "answer",
    "apart",
    "apollo",
    "appeal",
    "appear",
    "apple",
    "apply",
    "april",
    "arcade",
    "arctic",
    "arena",
    "argue",
    "armor",
    "army",
    "around",
    "arrange",
    "arrest",
    "arrive",
    "arrow",
    "artist",
    "artwork",
    "aspect",
    "assert",
    "asset",
    "assign",
    "assist",
    "assume",
    "assure",
    "athlete",
    "atlas",
    "atomic",
    "attach",
    "attack",
    "attain",
    "attempt",
    "attend",
    "august",
    "author",
    "autumn",
    "avatar",
    "avenue",
    "avoid",
    "awake",
    "award",
    "aware",
    "backup",
    "badge",
    "badger",
    "balance",
    "banana",
    "banner",
    "baron",
    "barrel",
    "barrier",
    "basket",
    "battle",
    "beacon",
    "beast",
    "beauty",
    "become",
    "before",
    "begin",
    "behalf",
    "behave",
    "behind",
    "belief",
    "belong",
    "beloved",
    "below",
    "benefit",
    "beside",
    "better",
    "beyond",
    "billion",
    "bishop",
    "bitter",
    "black",
    "blade",
    "blanket",
    "blaze",
    "blend",
    "bless",
    "blind",
    "block",
    "blonde",
    "blood",
    "bloom",
    "blueprint",
    "board",
    "boast",
    "border",
    "bottle",
    "bottom",
    "bounce",
    "boundary",
    "branch",
    "brave",
    "bread",
    "break",
    "breeze",
    "bridge",
    "bright",
    "broken",
    "bronze",
    "brother",
    "brown",
    "bubble",
    "bucket",
    "budget",
    "buffer",
    "build",
    "bullet",
    "bundle",
    "burden",
    "butter",
    "button",
    "cabin",
    "cabinet",
    "cable",
    "cactus",
    "calm",
    "camera",
    "campaign",
    "campus",
    "canal",
    "cancel",
    "candle",
    "candy",
    "canvas",
    "canyon",
    "capital",
    "captain",
    "carbon",
    "career",
    "cargo",
    "carpet",
    "carrier",
    "castle",
    "casual",
    "catalog",
    "catch",
    "cattle",
    "causal",
    "caution",
    "cave",
    "ceiling",
    "center",
    "century",
    "cereal",
    "certain",
    "chain",
    "chair",
    "chalk",
    "chamber",
    "chance",
    "change",
    "channel",
    "chaos",
    "chapter",
    "charge",
    "charm",
    "chart",
    "chase",
    "cheap",
    "check",
    "cheese",
    "cherry",
    "chest",
    "chief",
    "child",
    "choice",
    "choose",
    "chronic",
    "church",
    "cinema",
    "circle",
    "circuit",
    "citizen",
    "citrus",
    "civil",
    "claim",
    "clarity",
    "classic",
    "clean",
    "clear",
    "clerk",
    "clever",
    "client",
    "cliff",
    "climate",
    "climb",
    "clinic",
    "clock",
    "close",
    "cloth",
    "cloud",
    "cluster",
    "coach",
    "coast",
    "cobalt",
    "coffee",
    "cohort",
    "collar",
    "colleague",
    "collect",
    "college",
    "colony",
    "color",
    "column",
    "combat",
    "combine",
    "comedy",
    "comfort",
    "comic",
    "command",
    "comment",
    "commit",
    "common",
    "compact",
    "company",
    "compare",
    "compass",
    "compel",
    "comply",
    "compose",
    "compute",
    "concept",
    "concert",
    "conclude",
    "concrete",
    "condemn",
    "conduct",
    "confer",
    "confess",
    "confirm",
    "conflict",
    "conform",
    "confuse",
    "connect",
    "consent",
    "consist",
    "console",
    "constant",
    "consult",
    "consume",
    "contact",
    "contain",
    "content",
    "contest",
    "context",
    "continue",
    "contract",
    "contrast",
    "control",
    "convert",
    "convey",
    "convince",
    "cookie",
    "copper",
    "corner",
    "corona",
    "correct",
    "corridor",
    "cosmic",
    "costume",
    "cottage",
    "cotton",
    "couch",
    "council",
    "counsel",
    "counter",
    "country",
    "county",
    "couple",
    "courage",
    "course",
    "cousin",
    "cover",
    "cradle",
    "craft",
    "crater",
    "crazy",
    "cream",
    "create",
    "credit",
    "creek",
    "crew",
    "cricket",
    "crime",
    "crisis",
    "critic",
    "crown",
    "crucial",
    "cruise",
    "crunch",
    "crystal",
    "cube",
    "culture",
    "curious",
    "current",
    "curse",
    "curtain",
    "custom",
    "cyber",
    "cycle",
    "cylinder",
    "damage",
    "dancer",
    "danger",
    "daring",
    "darkness",
    "dawn",
    "daylight",
    "deadline",
    "debate",
    "decade",
    "decay",
    "december",
    "decide",
    "decimal",
    "declare",
    "decline",
    "decorate",
    "decrease",
    "dedicate",
    "defeat",
    "defect",
    "defend",
    "defense",
    "deficit",
    "define",
    "degree",
    "delay",
    "delegate",
    "delight",
    "deliver",
    "demand",
    "demise",
    "denial",
    "dense",
    "dentist",
    "depart",
    "depend",
    "deposit",
    "depth",
    "deputy",
    "derive",
    "desert",
    "design",
    "desire",
    "desktop",
    "despair",
    "destroy",
    "detail",
    "detect",
    "develop",
    "device",
    "devote",
    "diagram",
    "dialog",
    "diamond",
    "diary",
    "dictate",
    "differ",
    "digest",
    "digital",
    "dignity",
    "dilemma",
    "dinner",
    "diploma",
    "direct",
    "disable",
    "disaster",
    "discard",
    "disciple",
    "discover",
    "disease",
    "dish",
    "dismiss",
    "display",
    "dispute",
    "distance",
    "distinct",
    "distort",
    "district",
    "diverse",
    "divide",
    "divine",
    "divorce",
    "doctor",
    "doctrine",
    "document",
    "domain",
    "domestic",
    "dominant",
    "donate",
    "doorway",
    "double",
    "doubt",
    "dragon",
    "drain",
    "drama",
    "drastic",
    "dream",
    "dress",
    "drift",
    "drive",
    "driver",
    "drop",
    "drum",
    "dryer",
    "duck",
    "dull",
    "during",
    "dust",
    "duty",
    "dynamic",
    "eager",
    "eagle",
    "early",
    "earn",
    "earth",
    "easily",
    "eastern",
    "easy",
    "echo",
    "eclipse",
    "ecology",
    "economy",
    "edge",
    "edition",
    "editor",
    "educate",
    "effect",
    "effort",
    "eight",
    "either",
    "elder",
    "elect",
    "electric",
    "element",
    "elephant",
    "elevator",
    "elite",
    "embrace",
    "emerge",
    "emotion",
    "empire",
    "employ",
    "empower",
    "empty",
    "enable",
    "enact",
    "enclose",
    "encode",
    "encounter",
    "endless",
    "endorse",
    "endure",
    "enemy",
    "energy",
    "enforce",
    "engage",
    "engine",
    "enhance",
    "enjoy",
    "enlist",
    "enough",
    "enrich",
    "enroll",
    "ensure",
    "enter",
    "entire",
    "entry",
    "envelope",
    "episode",
    "equal",
    "equip",
    "equity",
    "erase",
    "error",
    "escape",
    "essay",
    "essence",
    "estate",
    "eternal",
    "ethics",
    "evidence",
    "evolve",
    "exact",
    "example",
    "exceed",
    "excel",
    "exchange",
    "excite",
    "exclude",
    "execute",
    "exempt",
    "exercise",
    "exhaust",
    "exhibit",
    "exile",
    "exist",
    "exit",
    "exotic",
    "expand",
    "expect",
    "expire",
    "explain",
    "explore",
    "export",
    "expose",
    "express",
    "extend",
    "extent",
    "extra",
    "extreme",
    "fabric",
    "facial",
    "factory",
    "faculty",
    "fade",
    "failure",
    "faith",
    "famous",
    "family",
    "fantasy",
    "farmer",
    "fashion",
    "fatal",
    "father",
    "fatigue",
    "fault",
    "favorite",
    "feature",
    "federal",
    "fellow",
    "female",
    "fence",
    "festival",
    "fiber",
    "fiction",
    "field",
    "figure",
    "filter",
    "final",
    "finance",
    "finger",
    "finish",
    "firewall",
    "fiscal",
    "flag",
    "flame",
    "flash",
    "flavor",
    "flee",
    "fleet",
    "flexible",
    "flight",
    "float",
    "flock",
    "floor",
    "fluid",
    "flush",
    "focus",
    "follow",
    "forbid",
    "force",
    "forecast",
    "foreign",
    "forest",
    "forever",
    "forge",
    "forget",
    "formal",
    "format",
    "fortune",
    "forward",
    "fossil",
    "foster",
    "founder",
    "fraction",
    "fragment",
    "frame",
    "freedom",
    "freeze",
    "frequent",
    "fresh",
    "friction",
    "friend",
    "frustrate",
    "fuel",
    "fulfill",
    "function",
    "fundamental",
    "funeral",
    "furnish",
    "further",
    "future",
    "galaxy",
    "gallery",
    "gamble",
    "garage",
    "garden",
    "garlic",
    "garment",
    "gateway",
    "gather",
    "gauge",
    "general",
    "genius",
    "genre",
    "gentle",
    "genuine",
    "gesture",
    "giant",
    "gift",
    "glance",
    "glare",
    "glide",
    "glimpse",
    "global",
    "glorious",
    "glory",
    "glove",
    "golden",
    "gospel",
    "govern",
    "grace",
    "gradual",
    "grain",
    "grand",
    "grant",
    "grape",
    "graph",
    "grasp",
    "grass",
    "gravity",
    "great",
    "grid",
    "grief",
    "grill",
    "ground",
    "group",
    "grow",
    "growth",
    "guarantee",
    "guard",
    "guess",
    "guide",
    "guild",
    "guilt",
    "guitar",
    "habitat",
    "habit",
    "hacker",
    "half",
    "hammer",
    "handbook",
    "handle",
    "handsome",
    "harbor",
    "hard",
    "hardware",
    "harmony",
    "harvest",
    "hazard",
    "headline",
    "health",
    "hearing",
    "heart",
    "heaven",
    "heavy",
    "height",
    "helmet",
    "helpful",
    "herald",
    "heritage",
    "hero",
    "hidden",
    "highlight",
    "highway",
    "history",
    "hobby",
    "hollow",
    "honest",
    "honey",
    "honor",
    "horizon",
    "horror",
    "horse",
    "hospital",
    "host",
    "hotel",
    "hound",
    "hover",
    "human",
    "humble",
    "humor",
    "hunger",
    "hunter",
    "hurdle",
    "hybrid",
    "hydro",
    "hygiene",
    "hypothesis",
    "icon",
    "ideal",
    "identity",
    "idle",
    "ignore",
    "illusion",
    "image",
    "immense",
    "impact",
    "impair",
    "imperial",
    "impose",
    "impress",
    "improve",
    "impulse",
    "incident",
    "income",
    "increase",
    "indeed",
    "index",
    "indicate",
    "indoor",
    "industry",
    "infant",
    "infer",
    "infinite",
    "inform",
    "inherit",
    "initial",
    "inject",
    "injure",
    "inland",
    "inmate",
    "inner",
    "innocent",
    "input",
    "inquire",
    "insight",
    "inspect",
    "inspire",
    "install",
    "instance",
    "instant",
    "instead",
    "instinct",
    "insult",
    "intact",
    "intake",
    "integer",
    "integrate",
    "integrity",
    "intend",
    "intense",
    "intent",
    "interest",
    "interior",
    "invest",
    "invite",
    "invoke",
    "involve",
    "island",
    "isolate",
    "issue",
    "item",
    "ivory",
    "jacket",
    "jaguar",
    "jail",
    "january",
    "jargon",
    "jasmine",
    "jealous",
    "jeep",
    "jelly",
    "jewel",
    "jockey",
    "joint",
    "joke",
    "journal",
    "journey",
    "judge",
    "juice",
    "july",
    "jumble",
    "jump",
    "jungle",
    "junior",
    "junk",
    "jury",
    "justice",
    "justify",
    "juvenile",
    "kangaroo",
    "keen",
    "keeper",
    "ketchup",
    "kettle",
    "keyboard",
    "kick",
    "kidnap",
    "kidney",
    "kingdom",
    "kitchen",
    "kitten",
    "knife",
    "knight",
    "knock",
    "knowledge",
    "label",
    "labor",
    "ladder",
    "lady",
    "lamp",
    "landing",
    "landscape",
    "lantern",
    "laptop",
    "laser",
    "launch",
    "laundry",
    "lavish",
    "lawyer",
    "layer",
    "layout",
    "leader",
    "league",
    "learn",
    "leather",
    "lecture",
    "legacy",
    "legend",
    "leisure",
    "lemon",
    "lender",
    "length",
    "lens",
    "leopard",
    "lesson",
    "letter",
    "level",
    "liberty",
    "library",
    "license",
    "liquid",
    "listen",
    "litter",
    "little",
    "lively",
    "lizard",
    "lobby",
    "lobster",
    "locate",
    "logic",
    "lonely",
    "lookup",
    "lottery",
    "lounge",
    "lumber",
    "luxury",
    "lyric",
    "machine",
    "magic",
    "magnet",
    "maid",
    "maintain",
    "major",
    "maker",
    "manage",
    "mandate",
    "manifest",
    "manner",
    "mansion",
    "manual",
    "marble",
    "margin",
    "marine",
    "market",
    "marshal",
    "matrix",
    "matter",
    "maximum",
    "meadow",
    "measure",
    "medal",
    "media",
    "melody",
    "member",
    "memory",
    "mentor",
    "menu",
    "mercy",
    "merge",
    "merit",
    "message",
    "metal",
    "method",
    "middle",
    "midnight",
    "million",
    "mineral",
    "minimal",
    "minimum",
    "minister",
    "minor",
    "minute",
    "miracle",
    "mirror",
    "misery",
    "missile",
    "mission",
    "mistake",
    "mixture",
    "mobile",
    "model",
    "modern",
    "modest",
    "modify",
    "module",
    "molecule",
    "moment",
    "monitor",
    "monkey",
    "monster",
    "monthly",
    "monument",
    "moral",
    "morning",
    "mortar",
    "mosaic",
    "mother",
    "motion",
    "motive",
    "mountain",
    "mouse",
    "movement",
    "movie",
    "muffin",
    "mule",
    "museum",
    "mushroom",
    "music",
    "mustard",
    "mutual",
    "mystery",
    "myth",
    "naked",
    "name",
    "napkin",
    "narrow",
    "nation",
    "native",
    "natural",
    "nature",
    "naval",
    "navigate",
    "near",
    "nebula",
    "necklace",
    "needle",
    "negative",
    "neglect",
    "negotiate",
    "neighbor",
    "nephew",
    "nerve",
    "nest",
    "network",
    "neutral",
    "never",
    "newly",
    "nexus",
    "nickel",
    "night",
    "noble",
    "noise",
    "nominate",
    "noodle",
    "normal",
    "northern",
    "notable",
    "note",
    "notice",
    "notify",
    "notion",
    "novel",
    "november",
    "nuclear",
    "number",
    "nurse",
    "nurture",
    "oasis",
    "object",
    "oblige",
    "obscure",
    "observe",
    "obtain",
    "obvious",
    "occasion",
    "occupy",
    "ocean",
    "october",
    "odor",
    "offense",
    "office",
    "officer",
    "offline",
    "offset",
    "olive",
    "olympic",
    "omit",
    "online",
    "onset",
    "open",
    "opera",
    "operate",
    "opinion",
    "opponent",
    "oppose",
    "optics",
    "option",
    "orange",
    "orbit",
    "orchestra",
    "order",
    "ordinary",
    "organ",
    "organic",
    "origin",
    "orphan",
    "ostrich",
    "other",
    "outdoor",
    "outer",
    "outfit",
    "outlet",
    "outline",
    "output",
    "outrage",
    "outside",
    "overall",
    "overcome",
    "overlap",
    "oversee",
    "oxygen",
    "oyster",
    "packet",
    "palace",
    "panel",
    "panic",
    "panther",
    "parade",
    "parcel",
    "parent",
    "park",
    "parrot",
    "partial",
    "partner",
    "passage",
    "passion",
    "passive",
    "pasta",
    "patch",
    "patent",
    "pathway",
    "patient",
    "patrol",
    "pattern",
    "pause",
    "pavement",
    "payment",
    "peace",
    "peanut",
    "peasant",
    "pebble",
    "peculiar",
    "pedal",
    "peer",
    "pelican",
    "penalty",
    "pencil",
    "penguin",
    "people",
    "pepper",
    "perfect",
    "perform",
    "period",
    "permit",
    "person",
    "pervade",
    "pioneer",
    "pipeline",
    "pistol",
    "pitch",
    "pixel",
    "planet",
    "plastic",
    "platform",
    "platinum",
    "plenty",
    "pocket",
    "poetry",
    "point",
    "poison",
    "policy",
    "polish",
    "politics",
    "pollen",
    "polygon",
    "portion",
    "portrait",
    "position",
    "positive",
    "possible",
    "postage",
    "potato",
    "potential",
    "poverty",
    "powder",
    "power",
    "practice",
    "praise",
    "predict",
    "prefer",
    "prepare",
    "present",
    "preserve",
    "preset",
    "pressure",
    "prevent",
    "preview",
    "previous",
    "price",
    "pride",
    "primary",
    "prime",
    "prince",
    "print",
    "priority",
    "prison",
    "privacy",
    "prize",
    "problem",
    "proceed",
    "process",
    "produce",
    "product",
    "profile",
    "profit",
    "program",
    "project",
    "promise",
    "promote",
    "prompt",
    "proper",
    "property",
    "propose",
    "protect",
    "proud",
    "provide",
    "proxy",
    "prune",
    "public",
    "publish",
    "pulse",
    "punch",
    "pupil",
    "puppy",
    "purchase",
    "pure",
    "purpose",
    "purse",
    "pursue",
    "puzzle",
    "pyramid",
    "quality",
    "quantum",
    "quarter",
    "queen",
    "query",
    "quest",
    "quick",
    "quiet",
    "quilt",
    "quota",
    "quote",
    "rabbit",
    "radar",
    "radiant",
    "radical",
    "radio",
    "railroad",
    "rainbow",
    "rally",
    "random",
    "range",
    "rapid",
    "rare",
    "raster",
    "ratify",
    "ratio",
    "razor",
    "react",
    "reader",
    "reality",
    "realm",
    "rebel",
    "rebuild",
    "recall",
    "receipt",
    "receive",
    "recipe",
    "record",
    "recover",
    "recruit",
    "recycle",
    "reduce",
    "reflect",
    "reform",
    "refuge",
    "refund",
    "refuse",
    "regard",
    "regime",
    "region",
    "register",
    "regret",
    "regular",
    "reject",
    "relate",
    "relax",
    "release",
    "relief",
    "rely",
    "remain",
    "remark",
    "remedy",
    "remind",
    "remote",
    "remove",
    "render",
    "renew",
    "repair",
    "repeat",
    "replace",
    "reply",
    "report",
    "rescue",
    "research",
    "reserve",
    "reset",
    "resist",
    "resolve",
    "resort",
    "resource",
    "respect",
    "respond",
    "restore",
    "result",
    "resume",
    "retail",
    "retain",
    "retire",
    "retreat",
    "return",
    "reveal",
    "revenue",
    "reverse",
    "review",
    "revise",
    "revive",
    "reward",
    "rhythm",
    "ribbon",
    "rider",
    "ridge",
    "rifle",
    "rigid",
    "ring",
    "riot",
    "ripple",
    "risk",
    "ritual",
    "rival",
    "river",
    "road",
    "robot",
    "robust",
    "rocket",
    "romance",
    "rookie",
    "rooster",
    "rotate",
    "rough",
    "round",
    "route",
    "routine",
    "royal",
    "rubber",
    "rugby",
    "ruin",
    "ruler",
    "rumor",
    "runner",
    "rural",
    "sacred",
    "saddle",
    "sadness",
    "safety",
    "sailor",
    "salad",
    "salmon",
    "salute",
    "sample",
    "sand",
    "satellite",
    "satisfy",
    "sauce",
    "sausage",
    "scale",
    "scan",
    "scatter",
    "scene",
    "scheme",
    "school",
    "science",
    "scissors",
    "scooter",
    "scope",
    "score",
    "scramble",
    "screen",
    "script",
    "scroll",
    "sculpture",
    "season",
    "section",
    "sector",
    "secure",
    "sedan",
    "seed",
    "seeker",
    "segment",
    "select",
    "seller",
    "semester",
    "seminar",
    "senior",
    "sense",
    "sensor",
    "sentence",
    "sequence",
    "series",
    "serious",
    "sermon",
    "serum",
    "session",
    "settle",
    "setup",
    "shadow",
    "shaft",
    "shallow",
    "shape",
    "share",
    "shark",
    "sharp",
    "shelter",
    "sheriff",
    "shield",
    "shift",
    "shine",
    "ship",
    "shiver",
    "shock",
    "shoot",
    "shore",
    "short",
    "shoulder",
    "shout",
    "shrimp",
    "shrine",
    "shuffle",
    "sibling",
    "sight",
    "signal",
    "signature",
    "silence",
    "silent",
    "silver",
    "similar",
    "simple",
    "simulate",
    "single",
    "sister",
    "situate",
    "sketch",
    "skill",
    "skirt",
    "skull",
    "slogan",
    "slot",
    "small",
    "smart",
    "smile",
    "smoke",
    "smooth",
    "snake",
    "snap",
    "snack",
    "sniper",
    "snow",
    "soap",
    "soccer",
    "social",
    "society",
    "socket",
    "sodium",
    "solar",
    "soldier",
    "solid",
    "solution",
    "solve",
    "somewhere",
    "sonic",
    "sorrow",
    "soul",
    "source",
    "southern",
    "space",
    "spark",
    "speaker",
    "special",
    "species",
    "specify",
    "spectacle",
    "spectrum",
    "speed",
    "sphere",
    "spider",
    "spike",
    "spinach",
    "spirit",
    "splash",
    "sponsor",
    "spoon",
    "sport",
    "spot",
    "spray",
    "spread",
    "spring",
    "squad",
    "square",
    "squeeze",
    "squirrel",
    "stable",
    "stadium",
    "stage",
    "stamp",
    "stand",
    "standard",
    "staple",
    "start",
    "state",
    "static",
    "statue",
    "status",
    "stay",
    "steam",
    "steel",
    "stem",
    "step",
    "stereo",
    "stick",
    "sticky",
    "stimulate",
    "stock",
    "stomach",
    "stone",
    "storage",
    "storm",
    "story",
    "strategy",
    "street",
    "strike",
    "string",
    "strip",
    "stroke",
    "structure",
    "struggle",
    "student",
    "studio",
    "stuff",
    "stumble",
    "style",
    "subject",
    "submit",
    "substance",
    "subtle",
    "subway",
    "success",
    "sudden",
    "suffer",
    "sugar",
    "suggest",
    "suit",
    "suitcase",
    "sulfur",
    "summer",
    "summit",
    "sunlight",
    "sunrise",
    "sunset",
    "sunshine",
    "super",
    "supply",
    "support",
    "suppose",
    "supreme",
    "surface",
    "surgeon",
    "surprise",
    "surround",
    "survey",
    "survive",
    "suspect",
    "sustain",
    "swallow",
    "swamp",
    "swap",
    "swarm",
    "swear",
    "sweet",
    "swift",
    "swim",
    "swing",
    "switch",
    "symbol",
    "symptom",
    "syrup",
    "system",
    "table",
    "tackle",
    "tactics",
    "talent",
    "target",
    "tariff",
    "taste",
    "tattoo",
    "tax",
    "teacher",
    "team",
    "teapot",
    "technical",
    "technique",
    "telegraph",
    "telescope",
    "temper",
    "temple",
    "tenant",
    "tennis",
    "tension",
    "terminal",
    "terrace",
    "terrible",
    "territory",
    "terror",
    "testify",
    "textile",
    "texture",
    "theater",
    "theory",
    "therapy",
    "thermal",
    "thesis",
    "thick",
    "thief",
    "think",
    "thirst",
    "threat",
    "threshold",
    "thrive",
    "throat",
    "thumb",
    "thunder",
    "ticket",
    "tide",
    "tiger",
    "timber",
    "timely",
    "timing",
    "tissue",
    "titan",
    "title",
    "toast",
    "tobacco",
    "toilet",
    "token",
    "tomato",
    "tomorrow",
    "tonight",
    "toolkit",
    "tooth",
    "topaz",
    "topic",
    "torch",
    "tornado",
    "torpedo",
    "tortoise",
    "total",
    "touch",
    "tough",
    "tourist",
    "toward",
    "tower",
    "town",
    "toxic",
    "tracer",
    "track",
    "trade",
    "traffic",
    "tragedy",
    "trail",
    "trailer",
    "train",
    "transfer",
    "transform",
    "transit",
    "translate",
    "transport",
    "trash",
    "travel",
    "tray",
    "tread",
    "treasure",
    "treat",
    "treaty",
    "tree",
    "tremble",
    "trench",
    "trend",
    "trial",
    "triangle",
    "tribe",
    "tribute",
    "trick",
    "trigger",
    "trim",
    "trip",
    "triple",
    "triumph",
    "trophy",
    "tropical",
    "trouble",
    "truck",
    "true",
    "trumpet",
    "trunk",
    "trust",
    "truth",
    "tube",
    "tulip",
    "tumble",
    "tumor",
    "tunnel",
    "turbine",
    "turkey",
    "turnip",
    "turtle",
    "twelve",
    "twenty",
    "twice",
    "twilight",
    "twist",
    "tycoon",
    "type",
    "typhoon",
    "typical",
    "ugly",
    "ultimate",
    "umbrella",
    "unable",
    "unaware",
    "uncle",
    "uncover",
    "under",
    "undo",
    "unfair",
    "unfold",
    "unhappy",
    "uniform",
    "unique",
    "unit",
    "universe",
    "unknown",
    "unlock",
    "unpack",
    "update",
    "upgrade",
    "uphold",
    "upload",
    "upon",
    "upper",
    "upset",
    "urban",
    "urge",
    "urgent",
    "usage",
    "useful",
    "useless",
    "user",
    "utility",
    "vacant",
    "vacuum",
    "vague",
    "valid",
    "valley",
    "valve",
    "vanish",
    "vapor",
    "variety",
    "various",
    "vault",
    "vector",
    "vehicle",
    "velvet",
    "vendor",
    "venture",
    "verdict",
    "verify",
    "verse",
    "version",
    "vessel",
    "veteran",
    "viable",
    "vibrant",
    "vicious",
    "victim",
    "victory",
    "video",
    "view",
    "village",
    "vintage",
    "violate",
    "violet",
    "violin",
    "viral",
    "virtual",
    "virtue",
    "virus",
    "visible",
    "vision",
    "visit",
    "visual",
    "vital",
    "vivid",
    "vocal",
    "voice",
    "volume",
    "volunteer",
    "vortex",
    "voter",
    "voyage",
    "vulture",
    "waffle",
    "wagon",
    "waiter",
    "walnut",
    "warrior",
    "wash",
    "water",
    "waveform",
    "weapon",
    "weather",
    "webmaster",
    "wedding",
    "weekend",
    "welcome",
    "welfare",
    "western",
    "wheel",
    "whisper",
    "whistle",
    "whole",
    "widget",
    "wilderness",
    "wildlife",
    "window",
    "winner",
    "winter",
    "wireless",
    "wisdom",
    "wizard",
    "wolf",
    "woman",
    "wooden",
    "worker",
    "world",
    "worship",
    "worthy",
    "wreck",
    "wrist",
    "writer",
    "yacht",
    "yard",
    "year",
    "yellow",
    "yield",
    "young",
    "youth",
    "zebra",
    "zenith",
    "zero",
    "zigzag",
    "zinc",
    "zipper",
    "zodiac",
    "zone",
)


# Sensitive credential / PII field names to scan in payload keys
_SENSITIVE_KEY_NAMES: Set[str] = {
    "password",
    "passwd",
    "pwd",
    "secret",
    "ssn",
    "social_security",
    "social_security_number",
    "credit_card",
    "creditcard",
    "card_number",
    "cc_num",
    "cc_number",
    "cvv",
    "cvc",
    "api_key",
    "apikey",
    "private_key",
    "privatekey",
    "secret_key",
    "secretkey",
    "access_token",
    "auth_token",
    "bearer_token",
    "pin",
    "pincode",
    "bank_account",
    "account_number",
    "routing_number",
    "session_token",
    "client_secret",
}

# Regex patterns for sensitive data in payload values
_REGEX_PATTERNS = {
    "SSN": (re.compile(r"\b\d{3}-\d{2}-\d{4}\b"), "US Social Security Number format"),
    "Credit Card": (
        re.compile(r"\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|6(?:011|5[0-9]{2})[0-9]{12})\b"),
        "Major Credit Card number (Visa, MC, Amex, Discover)",
    ),
    "Private Key": (
        re.compile(r"-----BEGIN (?:[A-Z0-9_-]+ )?PRIVATE KEY-----"),
        "Unencrypted Private Key PEM block",
    ),
    "AWS Access Key": (re.compile(r"\bAKIA[0-9A-Z]{16}\b"), "AWS Access Key ID"),
    "GitHub Token": (re.compile(r"\bghp_[0-9a-zA-Z]{36}\b"), "GitHub Personal Access Token"),
}


def _find_pii_in_dict(
    data: Any,
    path: str = "",
) -> List[Tuple[str, str, str]]:
    """Recursively search dictionary/list for sensitive keys and regex matches.

    Returns:
        List of (field_path, match_type, description)
    """
    findings: List[Tuple[str, str, str]] = []

    if isinstance(data, dict):
        for k, v in data.items():
            current_path = f"{path}.{k}" if path else str(k)
            k_lower = str(k).lower().replace("-", "_").replace(" ", "_")

            if k_lower in _SENSITIVE_KEY_NAMES or any(sk in k_lower for sk in ("password", "secret", "private_key")):
                findings.append((current_path, "Sensitive Key Name", f"Field '{k}' indicates stored credentials/secrets"))

            findings.extend(_find_pii_in_dict(v, current_path))

    elif isinstance(data, list):
        for idx, item in enumerate(data):
            findings.extend(_find_pii_in_dict(item, f"{path}[{idx}]"))

    elif isinstance(data, str):
        for pii_type, (regex, desc) in _REGEX_PATTERNS.items():
            if regex.search(data):
                findings.append((path, pii_type, f"Value matches {desc}"))

    return findings


def audit_jwt(
    token: Union[str, DecodedJWT],
    secret_wordlist: Optional[List[str]] = None,
    current_time: Optional[float] = None,
) -> SecurityAuditReport:
    """Perform a comprehensive security audit of a JWT/JWS token.

    Evaluates cryptographic algorithm security, header injection vectors (kid/jku/x5u),
    weak HMAC dictionary secrets, sensitive PII/credential exposures in unencrypted payloads,
    and token expiration lifetimes.

    Args:
        token: Raw token string or parsed DecodedJWT object.
        secret_wordlist: Optional custom wordlist of candidate secrets to test.
        current_time: Reference timestamp for expiration calculations.

    Returns:
        SecurityAuditReport: Aggregate risk score, risk level, vulnerability details,
        claims presence breakdown, entropy score, and cracked weak secret info.
    """
    now = time.time() if current_time is None else float(current_time)

    if isinstance(token, DecodedJWT):
        decoded = token
    else:
        decoded = parse_jwt(token)

    vulnerabilities: List[SecurityVulnerability] = []
    claims_checks: Dict[str, bool] = {
        "exp_present": False,
        "nbf_present": False,
        "iat_present": False,
        "iss_present": False,
        "aud_present": False,
        "sub_present": False,
        "jti_present": False,
    }

    raw_token = decoded.raw_token
    header = decoded.header
    payload = decoded.payload
    header_b64 = decoded.header_b64
    payload_b64 = decoded.payload_b64
    sig_b64 = decoded.signature_b64

    # Calculate Shannon Entropy
    entropy_score = calculate_token_entropy(raw_token)

    # If the token is not well-formed
    if not decoded.is_valid_format:
        vulnerabilities.append(
            SecurityVulnerability(
                severity=SecuritySeverity.CRITICAL,
                title="Malformed Token Format",
                cve_id=None,
                description=decoded.error_message or "The token fails basic JWT segment and JSON decoding rules.",
                impact="Unparseable tokens can cause unexpected server crashes, unhandled exceptions, or bypasses.",
                remediation="Ensure tokens follow RFC 7519 standard structure (Header.Payload.Signature).",
            )
        )
        return SecurityAuditReport(
            overall_risk_score=95,
            risk_level="CRITICAL",
            vulnerabilities=vulnerabilities,
            claims_checks=claims_checks,
            entropy_score=entropy_score,
            weak_secret_detected=False,
            detected_secret=None,
        )

    # 1. Algorithm "none" Vulnerability Check (CVE-2015-9235)
    alg_str = header.get("alg")
    if alg_str is None:
        vulnerabilities.append(
            SecurityVulnerability(
                severity=SecuritySeverity.CRITICAL,
                title="Missing Algorithm Header ('alg')",
                cve_id="CVE-2015-9235",
                description="The token header does not specify an 'alg' claim. Some libraries default to unsigned 'none'.",
                impact="Potential signature bypass if the backend accepts unverified default algorithms.",
                remediation="Explicitly require and validate a cryptographic algorithm in the header (e.g. HS256, RS256).",
            )
        )
    else:
        cleaned_alg = str(alg_str).strip()
        if cleaned_alg.lower() == "none" or cleaned_alg == "":
            vulnerabilities.append(
                SecurityVulnerability(
                    severity=SecuritySeverity.CRITICAL,
                    title="Critical Algorithm 'none' Bypass Vulnerability (CVE-2015-9235)",
                    cve_id="CVE-2015-9235",
                    description=(
                        f"The token header specifies 'alg': '{alg_str}'. An attacker can forge arbitrary payloads "
                        "and tamper with claims without possessing any secret key."
                    ),
                    impact="Complete authentication and authorization bypass; arbitrary administrative privilege escalation.",
                    remediation="Strictly disallow and reject tokens with alg='none' across all production verification filters.",
                )
            )

    # 2. Key Confusion and Header Injection Checks
    # 2a. Kid Path Traversal / SQL Injection
    kid = header.get("kid")
    if kid is not None and isinstance(kid, str):
        if "../" in kid or "..\\" in kid or kid.startswith("/etc/") or kid.startswith("/dev/null"):
            vulnerabilities.append(
                SecurityVulnerability(
                    severity=SecuritySeverity.CRITICAL,
                    title="Path Traversal Vector in 'kid' Header",
                    cve_id="CWE-22 / CWE-23",
                    description=f"The Key ID header parameter ('kid': {kid!r}) contains path traversal sequences.",
                    impact="Attackers may force the server to load arbitrary local files (e.g. /dev/null, known static files) as HMAC secrets.",
                    remediation="Sanitize and validate 'kid' against a whitelist of known key identifiers; avoid filesystem lookups using raw kid values.",
                )
            )
        elif any(sqli in kid.upper() for sqli in ("' OR '1'='1", "UNION SELECT", "DROP TABLE", "--", "';")):
            vulnerabilities.append(
                SecurityVulnerability(
                    severity=SecuritySeverity.HIGH,
                    title="SQL Injection Pattern in 'kid' Header",
                    cve_id="CWE-89",
                    description=f"The Key ID header parameter ('kid': {kid!r}) contains SQL injection syntax.",
                    impact="Potential database compromise if backend uses raw 'kid' in dynamic SQL queries.",
                    remediation="Use parameterized database queries when looking up cryptographic keys by 'kid'.",
                )
            )

    # 2b. JKU / X5U SSRF Risk
    for url_header in ("jku", "x5u"):
        if url_header in header:
            vulnerabilities.append(
                SecurityVulnerability(
                    severity=SecuritySeverity.HIGH,
                    title=f"Remote Key URL Header Detected ('{url_header}')",
                    cve_id="CWE-918",
                    description=(
                        f"The header contains '{url_header}': '{header[url_header]}'. If the server fetches this URL without "
                        "strict domain whitelisting, attackers can supply rogue public keys."
                    ),
                    impact="Server-Side Request Forgery (SSRF) and complete signature verification spoofing.",
                    remediation=f"Validate '{url_header}' against an immutable whitelist of trusted issuer domains, or disable remote JWKS fetching.",
                )
            )

    # 2c. Embedded JWK Header ('jwk')
    if "jwk" in header:
        vulnerabilities.append(
            SecurityVulnerability(
                severity=SecuritySeverity.HIGH,
                title="Embedded Public Key in Header ('jwk')",
                cve_id="CWE-347",
                description="The token supplies its own embedded verification key in the 'jwk' header parameter.",
                impact="If the server trusts self-signed embedded keys, attackers can generate their own keypair and sign valid tokens.",
                remediation="Never trust the embedded 'jwk' header for verification unless verified against a local certificate authority.",
            )
        )

    # 2d. Public Key confused as HMAC Secret / Asymmetric Confusion
    # Check if header is HMAC (HS256) but contains asymmetric parameters
    if alg_str and str(alg_str).upper() in ("HS256", "HS384", "HS512"):
        if any(k in header for k in ("x5c", "x5t", "jwk", "jku", "x5u")):
            vulnerabilities.append(
                SecurityVulnerability(
                    severity=SecuritySeverity.HIGH,
                    title="Asymmetric Header Claims on Symmetric HMAC Algorithm",
                    cve_id="CVE-2016-5431",
                    description="Token uses symmetric HMAC algorithm but includes asymmetric public key header attributes (e.g. x5c, jwk).",
                    impact="Indicates potential Key Confusion attack where public keys are treated as HMAC shared secrets.",
                    remediation="Enforce expected algorithm per endpoint; verify public keys are not passed to HMAC verifiers.",
                )
            )

    # 2e. Public Key string inside payload/header
    raw_text_scan = f"{header_b64} {payload_b64} {str(header)} {str(payload)}"
    if "BEGIN PUBLIC KEY" in raw_text_scan or "BEGIN RSA PUBLIC KEY" in raw_text_scan:
        vulnerabilities.append(
            SecurityVulnerability(
                severity=SecuritySeverity.CRITICAL,
                title="Public Key Embedded in Token (Key Confusion Risk)",
                cve_id="CVE-2016-5431 / CWE-327",
                description="Public Key PEM strings found within token content. Often used in RSA-to-HMAC confusion exploits.",
                impact="Signature forgery if backend HMAC validator is tricked into using the public key as the secret.",
                remediation="Ensure asymmetric and symmetric verification pipelines are strictly segregated.",
            )
        )

    # 3. Signature Stripping Check
    if alg_str and str(alg_str).lower() != "none" and not sig_b64:
        vulnerabilities.append(
            SecurityVulnerability(
                severity=SecuritySeverity.CRITICAL,
                title="Stripped Signature on Cryptographic Algorithm",
                cve_id="CWE-347",
                description=f"Token header specifies '{alg_str}' but the signature segment is empty.",
                impact="Unsigned token will be accepted if signature verification is inadvertently skipped.",
                remediation="Ensure signature verification is mandatory and never bypassed on empty signature strings.",
            )
        )

    # 4. Weak Secret Dictionary Attack
    weak_secret_found = False
    cracked_secret: Optional[str] = None

    if alg_str and str(alg_str).upper() in ("HS256", "HS384", "HS512") and sig_b64:
        candidates = list(COMMON_SECRET_DICTIONARY)
        if secret_wordlist:
            candidates.extend(secret_wordlist)

        cracked_secret = crack_hmac_secret(
            header_b64=header_b64,
            payload_b64=payload_b64,
            signature_b64=sig_b64,
            alg=str(alg_str),
            wordlist=candidates,
        )

        if cracked_secret:
            weak_secret_found = True
            vulnerabilities.append(
                SecurityVulnerability(
                    severity=SecuritySeverity.CRITICAL,
                    title=f"Trivially Crackable HMAC Secret ('{cracked_secret}')",
                    cve_id="CWE-522 / CWE-326",
                    description=(
                        f"The HMAC signature was cracked against a common secret dictionary. The secret is '{cracked_secret}'."
                    ),
                    impact="Complete loss of token integrity. Any attacker can sign valid tokens with arbitrary permissions.",
                    remediation="Generate high-entropy secrets of at least 256 bits (32 random bytes, base64/hex encoded).",
                )
            )

    # 5. Sensitive PII / Credential Exposure in Payload
    pii_matches = _find_pii_in_dict(payload)
    if pii_matches:
        for path_name, match_type, desc in pii_matches:
            severity = SecuritySeverity.CRITICAL if match_type in ("Private Key", "AWS Access Key", "GitHub Token") else SecuritySeverity.HIGH
            vulnerabilities.append(
                SecurityVulnerability(
                    severity=severity,
                    title=f"Sensitive Credential / PII Leak at '{path_name}'",
                    cve_id="CWE-312 / CWE-359",
                    description=f"{match_type} found at '{path_name}': {desc}.",
                    impact="JWT payloads are only Base64URL-encoded, not encrypted. Sensitive data is visible to all intermediaries.",
                    remediation="Remove sensitive credentials and personal data from JWT payload. Use JWE encryption if confidential data must be stored.",
                )
            )

    # 6. Expiration & Lifetime Sanity Checks
    if isinstance(payload, dict):
        # Update claims presence dictionary
        claims_checks["exp_present"] = "exp" in payload
        claims_checks["nbf_present"] = "nbf" in payload
        claims_checks["iat_present"] = "iat" in payload
        claims_checks["iss_present"] = "iss" in payload
        claims_checks["aud_present"] = "aud" in payload
        claims_checks["sub_present"] = "sub" in payload
        claims_checks["jti_present"] = "jti" in payload

        # Check missing exp
        if "exp" not in payload:
            vulnerabilities.append(
                SecurityVulnerability(
                    severity=SecuritySeverity.HIGH,
                    title="Missing Expiration Claim ('exp')",
                    cve_id="CWE-613",
                    description="Token does not contain an 'exp' claim and will remain valid forever if not revoked.",
                    impact="Immortal tokens facilitate perpetual replay attacks if captured or logged.",
                    remediation="Include a short-lived 'exp' claim in all issued tokens (e.g. 15-60 minutes for access tokens).",
                )
            )
        elif isinstance(payload["exp"], (int, float)):
            exp_val = float(payload["exp"])

            # Check expired
            if exp_val < now:
                vulnerabilities.append(
                    SecurityVulnerability(
                        severity=SecuritySeverity.LOW,
                        title="Token is Expired",
                        cve_id=None,
                        description=f"Token expiration timestamp ({exp_val}) is in the past.",
                        impact="Expired tokens should be rejected by compliant resource servers.",
                        remediation="Issue a refreshed token.",
                    )
                )

            # Check excessive lifetime (> 365 days)
            ref_start = float(payload.get("iat", now))
            lifetime_days = (exp_val - ref_start) / 86400.0
            if lifetime_days > 365:
                vulnerabilities.append(
                    SecurityVulnerability(
                        severity=SecuritySeverity.MEDIUM,
                        title=f"Excessive Token Lifetime ({lifetime_days:.0f} days)",
                        cve_id="CWE-613",
                        description=f"Token expiration is set to {lifetime_days:.0f} days (> 1 year) in the future.",
                        impact="Prolonged exposure window for stolen or leaked access tokens.",
                        remediation="Limit access token lifetimes to short intervals and rely on refresh token rotation.",
                    )
                )

            # Chronological contradiction
            if "iat" in payload and isinstance(payload["iat"], (int, float)):
                iat_val = float(payload["iat"])
                if exp_val < iat_val:
                    vulnerabilities.append(
                        SecurityVulnerability(
                            severity=SecuritySeverity.HIGH,
                            title="Invalid Chronology ('exp' prior to 'iat')",
                            cve_id="CWE-345",
                            description=f"Token 'exp' ({exp_val}) is earlier than 'iat' ({iat_val}).",
                            impact="Indicates flawed token generation logic or timestamp tampering.",
                            remediation="Ensure 'exp' is always greater than 'iat' during token minting.",
                        )
                    )

    # Calculate Aggregate Risk Score & Level
    score = 0
    for v in vulnerabilities:
        score += v.severity.score_weight

    score = min(score, 100)

    if score >= 80:
        risk_level = "CRITICAL"
    elif score >= 50:
        risk_level = "HIGH"
    elif score >= 25:
        risk_level = "MEDIUM"
    elif score > 0:
        risk_level = "LOW"
    else:
        risk_level = "CLEAN"

    return SecurityAuditReport(
        overall_risk_score=score,
        risk_level=risk_level,
        vulnerabilities=vulnerabilities,
        claims_checks=claims_checks,
        entropy_score=entropy_score,
        weak_secret_detected=weak_secret_found,
        detected_secret=cracked_secret,
    )
